before_install:
- "sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended"
script:
- mkdir _build
- pdflatex -output-directory _build tex/main.tex
- pdflatex -output-directory _build tex/main.tex
deploy:
  provider: releases
  api_key:
    secure: [YOUR KEY]
  file:
  - _build/main.pdf
  skip_cleanup: true
  on:
    tags: true
